# chocolatey-test.yml
name: CI - build and test Chocolatey Packages

on:
  push:
    branches:
      - main

  # manual execution from the Actions tab
  workflow_dispatch: {}

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            feishin:      "feishin/**"
            audioling:    "audioling/**"
            ampcast:      "ampcast/**"
            quantum:      "quantum/**"
            rescuetime:   "rescuetime/**"
            potplayer:    "potplayer/**"
            notion:       "notion/**"

  build-test:
    needs: filter-changes
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        package: 
          ${{ fromJson(needs.filter-changes.outputs.changed) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package
        shell: pwsh
        working-directory: ./${{ matrix.package }}
        run: |
          .\build.ps1

      - name: Test install package
        shell: pwsh
        working-directory: ./${{ matrix.package }}
        run: |
          choco install ${{ matrix.package }} -s . --force -y --debug --verbose

      - name: Test uninstall package
        shell: pwsh
        working-directory: ./${{ matrix.package }}
        run: |
          choco uninstall ${{ matrix.package }} -y --debug --verbose
