name: Release – build, test & push Chocolatey package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true
        type: choice
        options:
          - feishin
          - audioling
          - ampcast
          - quantum
          - rescuetime
          - potplayer
          - notion

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build ${{ inputs.package }}
        shell: pwsh
        working-directory: ./${{ inputs.package }}
        run: |
          ./build.ps1

      - name: Install test
        shell: pwsh
        working-directory: ./${{ inputs.package }}
        run: |
          choco install ${{ inputs.package }} -s . --force -y --debug --verbose

      - name: Uninstall test
        shell: pwsh
        working-directory: ./${{ inputs.package }}
        run: |
          choco uninstall ${{ inputs.package }} -y --debug --verbose

      - name: Push to Chocolatey
        shell: pwsh
        working-directory: ./${{ inputs.package }}
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco push --source https://push.chocolatey.org/ --apikey $env:CHOCO_API_KEY
